<template functional>
    <svg
        width="18px"
        height="74px"
        viewBox="0 0 18 74"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        class="red-team-pager"
    >
        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g transform="translate(-1551.000000, -562.000000)" fill="#FFFFFF">
                <g transform="translate(1551.000000, 562.000000)">
                    <rect
                        opacity="0.3"
                        x="0"
                        y="0"
                        width="18"
                        height="2"
                    ></rect>
                    <rect
                        opacity="0.3"
                        x="0"
                        y="16"
                        width="18"
                        height="2"
                    ></rect>
                    <rect
                        opacity="0.3"
                        x="0"
                        y="30"
                        width="18"
                        height="2"
                    ></rect>
                    <rect
                        opacity="0.3"
                        x="0"
                        y="44"
                        width="18"
                        height="2"
                    ></rect>
                    <rect
                        opacity="0.3"
                        x="0"
                        y="58"
                        width="18"
                        height="2"
                    ></rect>
                    <rect
                        opacity="0.3"
                        x="0"
                        y="72"
                        width="18"
                        height="2"
                    ></rect>
                </g>
            </g>
        </g>
    </svg>
</template>
