<?php 
/**
 * Template Name: Partner Program
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages and that
 * other "pages" on your WordPress site will use a different template.
 *
 * @package WordPress
 * @subpackage Twenty_Sixteen
 * @since Twenty Sixteen 1.0
 */

get_header(); ?>

<div class="imgOverflow-partners">
	<div class="wrapper">
		<div class="box box_md">
			<div class="heading">
				<h1 class="heading-bd heading-bd_lg whiteTxt">
	                Synack Partner Network
	            </h1>
	            <div class="heading-divider">
                    <div class="ruler ruler_center">
                        <div class="ruler-icon">
                            <span class="icon icon_ruler">
                                <a class="icon-break-white"><img src="https://www.synack.com/wp-content/uploads/2017/08/syn-icon-break-white.png" alt="Synack" /></a>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="whiteTxt-banner">
                	<p><strong>Strategic. Effective. Trusted.</strong></p>
                </div>
                <div class="vR vR_x4 heading-text_wide">
		            <div class="moduleImgTxtHero-ft">
			            <a href="mailto:channel@synack.com" class="btn btn_reverse" style="margin-top:30px !important;">Partner with Synack</a>
					</div>
	        	</div>
            </div>
		</div>
	</div>
</div>

<div class="">
	<div class="overflow-white">
		<div class="wysiwyg">
			<div class="moduleTxtHero-bd">
				<div class="moduleFeaturePartners">
					<div class="flex-grid-fifths">
						<div class="flex-column"><a><img src="/wp-content/uploads/2017/08/MSFT-featureLogo.png" alt="Microsoft" /></a></div>
						<div class="flex-column"><a><img src="/wp-content/uploads/2017/08/HP-featureLogo.png" alt="HP" /></a></div>
						<div class="flex-column"><a><img src="/wp-content/uploads/2017/08/SAP-featureLogo.png" alt="SAP" /></a></div>
						<div class="flex-column fifths-Adjust"><a><img src="/wp-content/uploads/2017/09/AWS-featureLogo.png" alt="Amazon Web Services" /></a></div>
						<div class="flex-column fifths-Adjust"><a><img src="/wp-content/uploads/2017/09/GCloud-featureLogo.png" alt="Google Cloud" /></a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="wrapper">
	<div class="wrapper">
		<div class="box box_md">
			<div class="moduleTxtHero">
				<!-- Top Section -->
		        <div class="moduleTxtHero-hd">
		            <div class="heading">
		                <h2 class="heading-bd">
		                    A Program for Every Partner
		                </h2>
		                <div class="heading-divider">
		                    <div class="ruler ruler_center">
		                        <div class="ruler-icon">
		                            <span class="icon icon_ruler">
		                                <svg class="icon-inner">
		                                    <use xlink:href="#icon-ruler"></use>
		                                </svg>
		                            </span>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		        <div class="moduleTxtHero-bd">
					<div class="wysiwyg">
	                	<p><strong>Hacker-Powered, Partner-Delivered</strong></p>
	                	<p>Together we can offer a fully managed service that utilizes Synack’s crowd of highly vetted hackers, bug-bounty incentives, scalable technology, and custom analytics and reporting. As part of our ecosystem, you can help customers detect, verify, prioritize and mitigate exploitable vulnerabilities and the associated business risk before a catastrophic breach. Delivered through an easy-to-consume subscription model, the powerful insights generated by the Synack solution empower our partners to deliver more intelligent, targeted, and effective services to their customers.</p>
					</div>
				</div>
				<div class="heading-text heading-text_wide">
				    <div class="vR vR_x10">
			            <div class="blocks blocks_3up mix-blocks_1to3to3">
			                <div>
			                    <div class="tout-md tout-md_sm tout-md_noBottom">
			                        <img src="/wp-content/uploads/2016/10/icon-lock-shield.png" alt="Technology Partners">
			                    </div>
			                        <h3 class="tout-hd"><span style="color: #006bff;">Technology Partners:</span><br />Provide holistic security solutions to help customers protect their entire attack surface by integrating the best talent, software, and processes.</h3>
			                </div>
		                    <div>
		                        <div class="tout-md tout-md_sm tout-md_noBottom">
		                            <img src="/wp-content/uploads/2016/10/icon-financial-growth.png" alt="VARs and Distributors">
		                        </div>
		                        	<h3 class="tout-hd"><span style="color: #006bff;">VARs & Distributors:</span><br />Deliver valuable and innovative security services that scale to meet your customers’ security assessment needs.</h3>
		                    </div>
			                <div>
			                    <div class="tout-md tout-md_sm tout-md_noBottom">
			                        <img src="/wp-content/uploads/2017/03/icon-gearsSearch.png" alt="System Integrators and MSSPs">
			                    </div>
			                        <h3 class="tout-hd"><span style="color: #006bff;">System Integrators & MSSPs:</span><br />Leverage Synack’s security platform and the power of the Synack crowd to develop advanced and highly differentiated vulnerability discovery and management programs.</h3>
			                </div>
			            </div>
						<div class="vR vR_x4 heading-text_wide">
				            <div class="moduleImgTxtHero-ft">
					            <a href="mailto:julia@synack.com" class="btn btn_primary" style="margin-top:30px !important;">Partner with Synack</a>
		    				</div>
				        </div>
				    </div>
                </div>
			</div>
		</div>
	</div>
</div>

<?php get_template_part('parts/solutions/prefooter'); ?>
<?php get_footer(); ?>
